export default {
  login: 'rhoofr',
  id: 43919098,
  node_id: 'MDQ6VXNlcjQzOTE5MDk4',
  avatar_url: 'https://avatars.githubusercontent.com/u/43919098?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/rhoofr',
  html_url: 'https://github.com/rhoofr',
  followers_url: 'https://api.github.com/users/rhoofr/followers',
  following_url: 'https://api.github.com/users/rhoofr/following{/other_user}',
  gists_url: 'https://api.github.com/users/rhoofr/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/rhoofr/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/rhoofr/subscriptions',
  organizations_url: 'https://api.github.com/users/rhoofr/orgs',
  repos_url: 'https://api.github.com/users/rhoofr/repos',
  events_url: 'https://api.github.com/users/rhoofr/events{/privacy}',
  received_events_url: 'https://api.github.com/users/rhoofr/received_events',
  type: 'User',
  site_admin: false,
  name: 'Richard Hoofring',
  company: 'HoofSoft',
  blog: '',
  location: 'Erlanger, Ky',
  email: null,
  hireable: true,
  bio:
    'I am a full stack web developer specializing in JavaScript, Node.Js, React, and Mongo DB.',
  twitter_username: null,
  public_repos: 10,
  public_gists: 0,
  followers: 1,
  following: 6,
  created_at: '2018-10-07T00:00:27Z',
  updated_at: '2021-03-11T20:23:50Z'
};
